# chat-games 配置
spring:
  application:
    name: chat-games
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - optional:nacos:chat-common-${spring.profiles.active}.yml?group=CHAT&refreshEnabled=true
      - optional:nacos:chat-games-${spring.profiles.active}.yml?group=CHAT&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_ENABLED:false}
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        ip: ${NACOS_IP:}
      config:
        enabled: ${NACOS_ENABLED:false}
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        file-extension: yml
        group: CHAT

springdoc:
  api-docs:
    path: /games/v3/api-docs
  swagger-ui:
    path: /games/swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
